const sceneWidth = 1760;
const sceneHeight = 2416;

// Placement values are sourced from WHXY_latest.csv so tweaks stay centralized.
export const GAME_DATA = {
  scene: {
    width: sceneWidth,
    height: sceneHeight,
    backgroundSrc: "./assets_latest/bg.png",
  },
  animals: [
    {
      id: "a1",
      name: "Animal 1",
      imageSrc: "./assets_latest/a1.png",
      x: 77,
      y: 480,
      width: 369,
      height: 302,
      movementAxis: "x",
      zIndex: 1,
      coverId: null,
      found: false,
    },
    {
      id: "a2",
      name: "Animal 2",
      imageSrc: "./assets_latest/a2.png",
      x: 141,
      y: 1677,
      width: 174,
      height: 165,
      movementAxis: "x",
      zIndex: 2,
      coverId: "fg2",
      found: false,
    },
    {
      id: "a3",
      name: "Animal 3",
      imageSrc: "./assets_latest/a3.png",
      x: 536,
      y: 892,
      width: 81,
      height: 134,
      movementAxis: "x",
      zIndex: 3,
      coverId: "fg3",
      found: false,
    },
    {
      id: "a4",
      name: "Animal 4",
      imageSrc: "./assets_latest/a4.png",
      x: 135,
      y: 22,
      width: 600,
      height: 394,
      movementAxis: "x",
      zIndex: 4,
      coverId: null,
      found: false,
    },
    {
      id: "a5",
      name: "Animal 5",
      imageSrc: "./assets_latest/a5.png",
      x: 1595,
      y: 1946,
      width: 93,
      height: 161,
      movementAxis: "y",
      zIndex: 5,
      coverId: null,
      found: false,
    },
    {
      id: "a6",
      name: "Animal 6",
      imageSrc: "./assets_latest/a6.png",
      x: 1075,
      y: 1261,
      width: 468,
      height: 113,
      movementAxis: "x",
      zIndex: 6,
      coverId: "fg4",
      found: false,
    },
    {
      id: "a7",
      name: "Animal 7",
      imageSrc: "./assets_latest/a7.png",
      x: 262,
      y: 2107,
      width: 84,
      height: 92,
      movementAxis: "x",
      zIndex: 7,
      coverId: "fg1",
      found: false,
    },
    {
      id: "a8",
      name: "Animal 8",
      imageSrc: "./assets_latest/a8.png",
      x: 1512,
      y: 1619,
      width: 167,
      height: 218,
      movementAxis: "x",
      zIndex: 8,
      coverId: null,
      found: false,
    },
    {
      id: "a9",
      name: "Animal 9",
      imageSrc: "./assets_latest/a9.png",
      x: 1543,
      y: 892,
      width: 197,
      height: 425,
      movementAxis: "y",
      zIndex: 9,
      coverId: null,
      found: false,
    },
  ],
  covers: [
    {
      id: "fg1",
      name: "Cover 1",
      imageSrc: "./assets_latest/fg1.png",
      x: 156,
      y: 2065,
      width: 232,
      height: 192,
      zIndex: 21,
      state: "closed",
      openTimer: null,
    },
    {
      id: "fg2",
      name: "Cover 2",
      imageSrc: "./assets_latest/fg2.png",
      x: 123,
      y: 1613,
      width: 210,
      height: 229,
      zIndex: 22,
      state: "closed",
      openTimer: null,
    },
    {
      id: "fg3",
      name: "Cover 3",
      imageSrc: "./assets_latest/fg3.png",
      x: 513,
      y: 868,
      width: 119,
      height: 98,
      zIndex: 23,
      state: "closed",
      openTimer: null,
    },
    {
      id: "fg4",
      name: "Cover 4",
      imageSrc: "./assets_latest/fg4.png",
      x: 1030,
      y: 1245,
      width: 730,
      height: 326,
      zIndex: 24,
      state: "closed",
      openTimer: null,
    },
  ],
};
